# Generated by Django 3.2.8 on 2023-09-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20230907_1826'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('pizza_order', models.ManyToManyField(to='pizza.PizzaModel')),
            ],
        ),
        migrations.DeleteModel(
            name='ToppingsModel',
        ),
    ]
